const menu = document.getElementById("menu") //footer//
const cartBtn = document.getElementById("cart-btn") //adicionar no carrinho//
const cartModal = document.getElementById("cart-modal") // modal
const cartItemsContainer = document.getElementById("cart-items") //items do carrinho//
const cartTotal = document.getElementById("cart-total") //total de compras//
const checkoutBtn = document.getElementById("checkout-btn") //fechar a conta//
const closeModalBtn = document.getElementById("close-modal-btn") //sair do modal//
const closeCounter =  document.getElementById("cart-count")
const addressInput = document.getElementById("address")
const addressWarn = document.getElementById("address-warn")